simulation:
  steps_per_frame: 100
  max_frames: 1000
  fps: 30
  show_trails: true
  max_trail_length: 365
  num_background_stars: 200
  intruder_trail_n: 120
  intruder_activate_frame: 200
  intruder_deactivate_frame: 800

integration:
  epsilon_soft: 1.0e+6
  eta_timestep: 0.02
  dt_min: 1.0
  dt_max: 5000.0
  dt_initial: 100.0
  close_approach_factor: 5.0

diagnostics:
  conservation_tol: 1.0e-3
  log_every_steps: 100
  log_every_frames: 50

viz:
  ortho_proj: true
  view_elev_deg: 30
  view_azim_deg: -45
  initial_zoom_AU: 0.5
  max_zoom_AU: 50.0
  bg_color: [0.02, 0.02, 0.08]

intruder:
  approach_state:  # [x,y,z,vx,vy,vz] at activation
    - -3.0e11
    - 2.0e11
    - 5.0e10
    - 4.5e4
    - -3.5e4
    - -5.0e3
  parked_state:    # [x,y,z,vx,vy,vz] when deactivated/parked
    - 1.0e13
    - 1.0e13
    - 1.0e12
    - -1.0e3
    - -1.0e3
    - -1.0e2
